### ISSUE TITLE
Correct decompression for deflate?

### ISSUE THREAD

**Issue by sholladay** [sindresorhus/unzip-response#3]
If the response is [using deflate](https://github.com/sindresorhus/unzip-response/blob/master/index.js#L6), shouldn't it be processed with `zlib.createInflate()` instead of `zlib.createGunzip()`? There's also `zlib.createUnzip()`, which apparently attempts to autodetect which to use.

I am trying to figure out whether I can replace some homemade logic with `unzip-response`, but they differ in this respect.

**Comment by sindresorhus** [comment]
This is using `createUnzip`: https://github.com/sindresorhus/unzip-response/blob/7be82bb24217e07a37c2a807cde8f0f5bb66c760/index.js#L7

**Comment by sholladay** [comment]
Oops. I swear I saw a `G` in there. 0:)

So its auto detection seems to be reliable?

**Comment by kevva** [comment]
#5.
