### ISSUE TITLE
should not be called "unzip"

### ISSUE THREAD

**Issue by thejoshwolfe** [sindresorhus/unzip-response#7]
Unzip sounds like zipfiles, which is an archive format. This project is about deflating/decompressing/gunzipping, which about data compression.

When i [searched npm for unzip](https://www.npmjs.com/search?q=unzip), this project was the second​ result, even though it has nothing to do with the zipfile format.

There is a common misconception that "zipping" files means to compress them, when really it means to archive them (meaning bundle multiple files together as a single file), and compression may or may not happen in the process. and if compression does happen, it's the generic DEFLATE algorithm, which is also what gzip uses; it's not some "zip compression" algorithm that was designed for zipfiles.

I understand that it's logistically infeasible to rename the project at this point; you've got over 3 million downloads a month. At least could you update the description of the package and repository to say "inflate" or "decompress" instead of "unzip"?

Thanks for your time.

**Comment by sindresorhus** [comment]
I agree with your arguments and it's unfortunate it lands that high up in the search result. I'm a happy user of you ZIP modules. I named it `unzip-` as the Node.js API I'm using is called that: https://github.com/sindresorhus/unzip-response/blob/71858052fe94b89678d14ba54e8e96cacbda92c3/index.js#L11

**Comment by sindresorhus** [comment]
Renamed. Your project is now the second result: https://npms.io/search?q=unzip 😀

If you also think it's dumb that the first result is an unmaintained module, complain here: https://github.com/npms-io/npms-analyzer/issues/63

**Comment by sindresorhus** [comment]
@thejoshwolfe

**Comment by thejoshwolfe** [comment]
wow! thanks​.
